<a href="https://colab.research.google.com/github/naveensinghcr21/Image-Detection/blob/main/Heart_disease_prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

importing dependancies

In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score


In [2]:
heart_data= pd.read_csv("/content/drive/MyDrive/Colab Notebooks/heart.csv")

In [3]:
heart_data

age  sex  cp  trestbps  chol  fbs  ...  exang  oldpeak  slope  ca  thal  target
0     63    1   3       145   233    1  ...      0      2.3      0   0     1       1
1     37    1   2       130   250    0  ...      0      3.5      0   0     2       1
2     41    0   1       130   204    0  ...      0      1.4      2   0     2       1
3     56    1   1       120   236    0  ...      0      0.8      2   0     2       1
4     57    0   0       120   354    0  ...      1      0.6      2   0     2       1
..   ...  ...  ..       ...   ...  ...  ...    ...      ...    ...  ..   ...     ...
298   57    0   0       140   241    0  ...      1      0.2      1   0     3       0
299   45    1   3       110   264    0  ...      0      1.2      1   0     3       0
300   68    1   0       144   193    1  ...      0      3.4      1   2     3       0
301   57    1   0       130   131    0  ...      1      1.2      1   1     3       0
302   57    0   1       130   236    0  ...      0      0.0      1   1     2       0

[303 rows x 14 columns]

In [4]:
heart_data.shape

(303, 14)

checking number of missing values

In [5]:
heart_data.isna().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [6]:
#statistical measure about the data

In [7]:
heart_data.describe()

age         sex          cp  ...          ca        thal      target
count  303.000000  303.000000  303.000000  ...  303.000000  303.000000  303.000000
mean    54.366337    0.683168    0.966997  ...    0.729373    2.313531    0.544554
std      9.082101    0.466011    1.032052  ...    1.022606    0.612277    0.498835
min     29.000000    0.000000    0.000000  ...    0.000000    0.000000    0.000000
25%     47.500000    0.000000    0.000000  ...    0.000000    2.000000    0.000000
50%     55.000000    1.000000    1.000000  ...    0.000000    2.000000    1.000000
75%     61.000000    1.000000    2.000000  ...    1.000000    3.000000    1.000000
max     77.000000    1.000000    3.000000  ...    4.000000    3.000000    1.000000

[8 rows x 14 columns]

number of people having heart disease

In [8]:
heart_data[heart_data.target == 1]["target"].count()

165

number of people not having heart disease

In [9]:
heart_data[heart_data.target == 0]["target"].count()

138

In [10]:
#OR
heart_data["target"].value_counts()

1    165
0    138
Name: target, dtype: int64

target = 1 means defective heart

target =2 means non defective heart

using all the features to predict the target.
Also we need to remove the target column and store it in seperate variable,since we need to predict the output

In [11]:
x=heart_data.drop(columns="target",axis=1)
y=heart_data["target"]

In [12]:
x

age  sex  cp  trestbps  chol  ...  exang  oldpeak  slope  ca  thal
0     63    1   3       145   233  ...      0      2.3      0   0     1
1     37    1   2       130   250  ...      0      3.5      0   0     2
2     41    0   1       130   204  ...      0      1.4      2   0     2
3     56    1   1       120   236  ...      0      0.8      2   0     2
4     57    0   0       120   354  ...      1      0.6      2   0     2
..   ...  ...  ..       ...   ...  ...    ...      ...    ...  ..   ...
298   57    0   0       140   241  ...      1      0.2      1   0     3
299   45    1   3       110   264  ...      0      1.2      1   0     3
300   68    1   0       144   193  ...      0      3.4      1   2     3
301   57    1   0       130   131  ...      1      1.2      1   1     3
302   57    0   1       130   236  ...      0      0.0      1   1     2

[303 rows x 13 columns]

In [13]:
y

0      1
1      1
2      1
3      1
4      1
      ..
298    0
299    0
300    0
301    0
302    0
Name: target, Length: 303, dtype: int64

now we need to feed these x and y to our machine learning model as a training data and test data

In [14]:
X_train,X_test,Y_train,Y_test=train_test_split(x,y,test_size=0.2,random_state=2,stratify=y)

In [15]:
X_train

age  sex  cp  trestbps  chol  ...  exang  oldpeak  slope  ca  thal
61    54    1   1       108   309  ...      0      0.0      2   0     3
238   77    1   0       125   304  ...      1      0.0      2   3     2
160   56    1   1       120   240  ...      0      0.0      0   0     2
158   58    1   1       125   220  ...      0      0.4      1   4     3
289   55    0   0       128   205  ...      1      2.0      1   1     3
..   ...  ...  ..       ...   ...  ...    ...      ...    ...  ..   ...
100   42    1   3       148   244  ...      0      0.8      2   2     2
49    53    0   0       138   234  ...      0      0.0      2   0     2
300   68    1   0       144   193  ...      0      3.4      1   2     3
194   60    1   2       140   185  ...      0      3.0      1   0     2
131   49    0   1       134   271  ...      0      0.0      1   0     2

[242 rows x 13 columns]

In [16]:
X_test

age  sex  cp  trestbps  chol  ...  exang  oldpeak  slope  ca  thal
255   45    1   0       142   309  ...      1      0.0      1   3     3
72    29    1   1       130   204  ...      0      0.0      2   0     2
83    52    1   3       152   298  ...      0      1.2      1   0     3
268   54    1   0       122   286  ...      1      3.2      1   2     2
92    52    1   2       138   223  ...      0      0.0      2   4     2
..   ...  ...  ..       ...   ...  ...    ...      ...    ...  ..   ...
42    45    1   0       104   208  ...      1      3.0      1   0     2
187   54    1   0       124   266  ...      1      2.2      1   1     3
8     52    1   2       172   199  ...      0      0.5      2   0     3
122   41    0   2       112   268  ...      1      0.0      2   0     2
19    69    0   3       140   239  ...      0      1.8      2   2     2

[61 rows x 13 columns]

In [17]:
Y_train

61     1
238    0
160    1
158    1
289    0
      ..
100    1
49     1
300    0
194    0
131    1
Name: target, Length: 242, dtype: int64

#need to train our machine learning model

we ll use logistic regression model as it is very useful for binary classification(target is either 1/0)

In [18]:
 #loading one instance of the variable class " logistic regression" to our new variable i.e model
 model = LogisticRegression()

In [19]:
#training the logistic regression model with training data
model.fit(X_train,Y_train) #model fitting with training data sets


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

model evaluation on how well it is performing

In [20]:
#accuracy on training data
x_train_target= model.predict(X_train)#storing predicted target value(many of those values will be matching Y_train values)
training_data_accuracy= accuracy_score(x_train_target,Y_train)#comparison is happening inside accuracy score function
training_data_accuracy


0.8512396694214877

so 85% our model is accurate

In [21]:
print("our model predicted with",training_data_accuracy *100 ,"percent of accuracy on training data")

our model predicted with 85.12396694214877 percent of accuracy on training data


#now we need to score accuracy score of test data

In [22]:
#accuracy on test data
x_test_target= model.predict(X_test)#storing predicted target value(many of those values will be matching Y_train values)
test_data_accuracy= accuracy_score(x_test_target,Y_test)#comparison is happening inside accuracy score function
test_data_accuracy


0.819672131147541

In [23]:
print("our model predicted with",test_data_accuracy *100 ,"percent of accuracy on test data")

our model predicted with 81.9672131147541 percent of accuracy on test data


#final step: going to build a predictive system

steps:
1. getting input features and using those predicting whether a person is having heart disease or not?

input data example

In [43]:
input_data1= (59,1,0,110,239,0,0,142,1,1.2,1,1,3,0)

taking input data from X_test data

In [53]:
input_data=tuple(X_test.iloc[56])
input_data

(45.0, 1.0, 0.0, 104.0, 208.0, 0.0, 0.0, 148.0, 1.0, 3.0, 1.0, 0.0, 2.0)

In [54]:
#change the input_data to numpy array since its in tuple form
input_data_as_numpy_array=np.asarray(input_data)

In [55]:
input_data_as_numpy_array

array([ 45.,   1.,   0., 104., 208.,   0.,   0., 148.,   1.,   3.,   1.,
         0.,   2.])

In [56]:
#reshaping because we need to tell our machine learning model that we need to predict output for only 1 dataset(or row value),instead of predicting for all values from data frame
input_data_reshaped=input_data_as_numpy_array.reshape(1,-1)

In [57]:
input_data_reshaped

array([[ 45.,   1.,   0., 104., 208.,   0.,   0., 148.,   1.,   3.,   1.,
          0.,   2.]])

In [58]:
model.predict(input_data_reshaped)

array([0])

In [59]:
if model.predict(input_data_reshaped) ==1:
  print("person is having heart disease")
else:
  print("person is safe")

person is safe
